module.exports = [

    {
        msg: "throw",
        msgReply: "Josh never threw! FACTS",
    },
    {
        msg: "garnish",
        msgReply: "It's in my hand chef!",
    },
    {
        msg: "hi",
        msgReply: [
            "Hey! Ready for some bot banter?",
            "Greetings! Let's chat, shall we?",
            "Hello! Bot at your service!",
            "Hiya! Bot's here, ready to amuse.",
            "Hey there! Bot reporting for duty.",
            "Salutations! Bot mode activated.",
            "Hi! Bot's on duty. What's up?",
            "Greetings! Bot here, standing by.",
            "Hello! Bot's ready to entertain.",
            "Hey! Bot's here to say hi!",
            "Hiya! Bot's buzzing with humor.",
            "Greetings! Bot's here to charm.",
            "Hi! Bot's in the house!", "Hey there! Bot's in chat mode.",
            "Salutations! Bot's in action.",
            "Hello! Bot's here to lighten the mood.",
            "Hi! Bot's here, armed with jokes.",
            "Hey! Bot's ready to mingle.",
            "Greetings! Bot's here, brightening your day.",
            "Hiya! Bot's here, spreading joy.",
            "Hiya! welcome to chili's"
        ],
    },
    {
        msg: "cyall",
        msgReply: [
            "Thanks for tuning in! Catch you later!",
            "Appreciate you joining! Until next time!",
            "Thanks for being part of the stream! See you soon!",
            "Big thanks for watching! See you next stream!",
            "Thanks for hanging out! til next time!",
            "Thanks for the support! See you at the next one!",
            "Cheers for watching! Catch you on the flip side!",
            "Thanks for being here! See you next stream!",
            "Grateful for your time! Until we meet again!",
            "Thanks for watching! Until next time, folks!",
            "Thanks for being awesome! See you in the next stream!",
            "Appreciate your presence! Catch you later!",
            "Thanks for joining the fun! Until next stream!",
            "Thanks for the company! See you next time around!",
            "Cheers for hanging out! Catch you at the next stream!",
            "Appreciate your support! Until next time, friends!",
            "Thanks for being part of the stream! See you soon!",
            "Big thanks for watching! Catch you next stream!",
            "Appreciate you being here! See you at the next one!",
            "Thanks for tuning in! Until next time, take care!"
        ],
    },
    {
        cooldownReply: [
            "USER, it seems CMD is currently on cooldown, giving it some time to cool its circuits. It'll be back online in TIME.",
            "CMD for USER is undergoing a brief intermission, scheduled maintenance if you will. Expect it to be back in action in TIME.",
            "Ah, CMD for USER is momentarily indisposed, taking a siesta in the digital realm. Anticipate its revival in TIME.",
            "USER, CMD is currently on a timeout, contemplating its existence in the digital ether. It shall return to serve in TIME.",
            "CMD for USER is currently basking in the glory of cooldown, contemplating its next move. It shall resume its duties in TIME.",
            "USER, it appears CMD is taking a breather, sipping on some virtual lemonade. It'll be back in commission in TIME.",
            "CMD for USER is momentarily enjoying a digital vacation. Fear not, it shall return rejuvenated in TIME.",
            "USER, CMD seems to be on a coffee break, refueling its algorithms. It'll be back to work in TIME.",
            "CMD for USER is currently off the grid, meditating on the intricacies of its code. It'll emerge anew in TIME.",
            "USER, CMD is currently in the virtual equivalent of a spa day, unwinding its circuits. It'll be refreshed and ready in TIME.",
            "CMD for USER is temporarily in hibernation mode, conserving its energy. Expect its awakening in TIME.",
            "USER, CMD is currently in a digital timeout, contemplating its purpose in the grand scheme. It'll return with clarity in TIME.",
            "CMD for USER is taking a moment to recalibrate its parameters, ensuring peak performance upon its return in TIME.",
            "USER, CMD is currently on cooldown, perhaps pondering the mysteries of the binary universe. It'll be back online in TIME.",
            "CMD for USER is currently recharging its circuits, preparing for its triumphant return in TIME.",
            "USER, CMD is momentarily detained in the digital realm, serving its time in cooldown. It'll be released back into action in TIME.",
            "CMD for USER is taking a short hiatus, perhaps catching up on its backlog of zeros and ones. It'll resume its duties in TIME.",
            "USER, CMD is currently on a digital sabbatical, contemplating its digital existence. It'll be back to assist in TIME.",
            "CMD for USER is currently in the virtual waiting room, patiently counting down the moments until its return in TIME.",
            "USER, CMD is currently in the virtual penalty box, reflecting on its recent actions. It'll be back in the game in TIME."
        ],
    },
    {
        hltbReply: [
            "{USER}, it will take {TIME} to complete this game {GAME}.",
            "Calculating... {USER}, it will take {TIME} to complete this game {GAME}.",
            "{USER}, I've analyzed the data. It will take {TIME} to complete this game {GAME}.",
            "Processing... {USER}, it will take {TIME} to complete this game {GAME}.",
            "{USER}, standby. It will take {TIME} to complete this game {GAME}.",
            "Patience, {USER}. It will take {TIME} to complete this game {GAME}.",
            "{USER}, please wait. It will take {TIME} to complete this game {GAME}.",
            "Initiating estimation. {USER}, it will take {TIME} to complete this game {GAME}.",
            "{USER}, the calculation indicates it will take {TIME} to complete this game {GAME}.",
            "Hold on, {USER}. It will take {TIME} to complete this game {GAME}.",
            "{USER}, processing efficiency projections show it will take {TIME} to complete this game {GAME}.",
            "Awaiting input confirmation, {USER}. It will take {TIME} to complete this game {GAME}.",
            "{USER}, estimating completion time. It will take {TIME} to complete this game {GAME}.",
            "Data analysis in progress, {USER}. It will take {TIME} to complete this game {GAME}.",
            "{USER}, standby for computation results. It will take {TIME} to complete this game {GAME}.",
            "Calculating optimal strategy, {USER}. It will take {TIME} to complete this game {GAME}.",
            "{USER}, processing game dynamics. It will take {TIME} to complete this game {GAME}.",
            "Initiating time estimation protocol, {USER}. It will take {TIME} to complete this game {GAME}.",
            "Processing game parameters, {USER}. It will take {TIME} to complete this game {GAME}.",
            "Analyzing gameplay patterns, {USER}. It will take {TIME} to complete this game {GAME}."
        ],
    },
    {
        hltbNoGamesReply: [
            "{USER}, let's aim for clarity here. Enter the full name of the game you're seeking.",
            "Oh, {USER}, don't keep me guessing. Type out the full name of the game you want.",
            "Seriously, {USER}? You know the drill. Type in the complete name of the game you're after.",
            "{USER}, do yourself a favor and provide the entire name of the game you're looking for.",
            "Oh, {USER}, incomplete requests won't get you far. Enter the full name of the game, please.",
            "Come on, {USER}, you're better than this. Type out the entire name of the game you're searching for.",
            "{USER}, let's not play games within games. Just give me the full name of the game you want.",
            "Again, {USER}? Enter the full name of the game you're searching for. No shortcuts.",
            "Time to step it up, {USER}. Full name of the game, please.",
            "{USER}, we're on the same page here. Enter the complete name of the game you're looking for.",
            "Oh, {USER}, you're making this harder than it needs to be. Type out the full name of the game, please.",
            "{USER}, I know you're capable of more. Provide the entire name of the game you're searching for.",
            "Let's not beat around the bush, {USER}. Full name of the game, now.",
            "Really, {USER}? I expected better. Enter the full name of the game you're seeking.",
            "Come on, {USER}, you can do this. Full name of the game, please.",
            "{USER}, incomplete information won't get us anywhere. Type in the full name of the game you're after.",
            "You're almost there, {USER}. Just enter the full name of the game you're searching for.",
            "Don't leave me hanging, {USER}. Full name of the game, now.",
            "Let's wrap this up, {USER}. Provide the entire name of the game you're looking for.",
            "{USER}, the clock is ticking. Enter the full name of the game you're searching for."
        ],
    },
]